config/routes.rb
ContactManager::Application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  resources :sessions, only: [:create, :destroy]

  match '/login' => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

  root :to => 'site#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	include Contact

  attr_accessible :first_name, :last_name, :user_id

  validates :first_name, :last_name, presence: true

  belongs_to :user

  def to_s
	  "#{last_name}, #{first_name}"
	end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_filter :find_resource, only: [:edit, :show, :update, :destroy]

  # GET /people
  # GET /people.json

  def index
    @people = current_user.people

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit

  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])
    @person.user = current_user

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td>
      <ul>
        <li><%= link_to 'Show', person %></li>
        <li><%= link_to 'Edit', edit_person_path(person) %></li>
        <li><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<ul>
	<%= render 'phone_numbers/phone_numbers', phone_numbers: @person.phone_numbers %>
</ul>

<ul>
	<%= render 'email_addresses/email_addresses', email_addresses: @person.email_addresses %>
</ul>

<%= link_to 'Add email id', new_email_address_path(contact_id: @person.id, contact_type: 'Person') %> |
<%= link_to 'Add phone number', new_phone_number_path(contact_id: @person.id, contact_type: 'Person') %> |
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>