config/routes.rb
ContactManager::Application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  resources :sessions, only: [:create, :destroy]

  match '/login' => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

  root :to => 'site#index'

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  attr_accessible :number, :contact_id, :contact_type

  validates :number, :contact_id, presence: true

  belongs_to :contact, polymorphic: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController

  before_filter :find_resource, except: [:new, :create]
 
  # GET /phone_numbers/new
  # GET /phone_numbers/new.json
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phone_number }
    end
  end

  # GET /phone_numbers/1/edit
  def edit
    
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(params[:phone_number])

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render json: @phone_number.contact, status: :created, location: @phone_number.contacts }
      else
        format.html { render action: "new" }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phone_numbers/1
  # PUT /phone_numbers/1.json
  def update


    respond_to do |format|
      if @phone_number.update_attributes(params[:phone_number])
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    
    @phone_number.destroy

    respond_to do |format|
      format.html { redirect_to @phone_number.contact }
      format.json { head :no_content }
    end
  end
end

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br />
    <%= f.number_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/_phone_numbers.html.erb
<% phone_numbers.each do |phone| %>
	<li><%= phone.number %> <%= link_to('Edit', edit_phone_number_path(phone)) %> | 
		<%= link_to 'Delete', phone, method: :delete, data: { confirm: 'Are you sure?' } %></li>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing phone_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/new.html.erb
<h1>New phone_number</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>