config/routes.rb
ContactManager::Application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  resources :sessions, only: [:create, :destroy]

  match '/login' => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

  root :to => 'site#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	include Contact
	
  attr_accessible :name, :user_id

  validates :name, presence: true

  belongs_to :user

  def to_s
  	"#{name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :find_resource, only: [:edit, :show, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])
    @company.user = current_user

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.haml
%h1 Listing companies

%table 
  %tr 
    %th Name
    %th 
 

-@companies.each do |company| 
  %tr 
    %td=company.name 
    %td 
      %ul 
        %li=link_to 'Show', company, class: 'actions' 
        %li=link_to 'Edit', edit_company_path(company), class: 'actions' \
        %li=link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'actions' 

%br 

=link_to 'New Company', new_company_path, id: 'new_company' 

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<ul>
	<%= render 'phone_numbers/phone_numbers', phone_numbers: @company.phone_numbers %>
	<%= render 'email_addresses/email_addresses', email_addresses: @company.email_addresses %>
</ul>

<ul>
	<li><%= link_to 'Add email id', new_email_address_path(contact_id: @company.id, contact_type: 'Company'), class: 'actions' %> |</li>
	<li><%= link_to 'Add Phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company'), class: 'actions' %> |</li>
	<li><%= link_to 'Edit', edit_company_path(@company), class: 'actions' %> |</li>
	<li><%= link_to 'Back', companies_path, class: 'actions' %></li>
</ul>