config/routes.rb
ContactManager::Application.routes.draw do
  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get '/auth/:provider/callback' => 'sessions#create'

  resources :sessions, only: [:create, :destroy]

  match '/login' => redirect("/auth/twitter"), as: :login

  delete "/logout" => "sessions#destroy", as: :logout

  root :to => 'site#index'

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController

  before_filter :find_resource, except: [:new, :create]

  # GET /email_addresses/new
  # GET /email_addresses/new.json
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_address }
    end
  end

  # GET /email_addresses/1/edit
  def edit
    
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(params[:email_address])

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render json: @email_address.contact, status: :created, location: @email_address.contacts }
      else
        format.html { render action: "new" }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_addresses/1
  # PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update_attributes(params[:email_address])
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy

    respond_to do |format|
      format.html { redirect_to @email_address.contact }
      format.json { head :no_content }
    end
  end
end

app/views/email_addresses/_email_addresses.html.erb
<% email_addresses.each do |email| %>
		<li><%= email.address %> <%= link_to('Edit', edit_email_address_path(email)) %> | 
			<%= link_to 'Delete', email, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	<% end %>

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <% if @email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% @email_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br />
    <%= f.number_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Editing email_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_address %> |
<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/new.html.erb
<h1><%= "New Email Address for #{@email_address.contact.to_s}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', email_addresses_path %>